steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest", "--cache-from", "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest", "."]
    id: build_image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "--env"
      - "GS_BUCKET_NAME=${_GS_BUCKET_NAME}"
      - "--env"
      - "DEBUG=${_DEBUG}"
      - "--env"
      - "SECRET_KEY=${_SECRET_KEY}"
      - "--env"
      - "GOOGLE_RECAPTCHA_SECRET_KEY=${_GOOGLE_RECAPTCHA_SECRET_KEY}"
      - "--network=cloudbuild"
      - "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"
      - "python"
      - "manage.py"
      - "test"
    id: test
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "--env"
      - "GS_BUCKET_NAME=${_GS_BUCKET_NAME}"
      - "--env"
      - "DEBUG=${_DEBUG}"
      - "--env"
      - "SECRET_KEY=${_SECRET_KEY}"
      - "--env"
      - "GOOGLE_RECAPTCHA_SECRET_KEY=${_GOOGLE_RECAPTCHA_SECRET_KEY}"
      - "--network=cloudbuild"
      - "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"
      - "python"
      - "manage.py"
      - "collectstatic"
      - "--noinput"
    id: collectstatic
    waitFor:
      - test
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "-d"
      - "-v"
      - "/cloudsql:/cloudsql"
      - "--network=cloudbuild"
      - "gcr.io/cloudsql-docker/gce-proxy"
      - "/cloud_sql_proxy"
      - "-dir=/cloudsql"
      - "-instances=cs130-268823:us-central1:wander-io-database"
    id: setup_db
    waitFor:
      - test
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "run"
      - "--env"
      - "DB_HOST=${_DB_HOST}"
      - "--env"
      - "DB_NAME=${_DB_NAME}"
      - "--env"
      - "DB_USER=${_DB_USER}"
      - "--env"
      - "DB_PASSWORD=${_DB_PASSWORD}"
      - "--env"
      - "DEBUG=${_DEBUG}"
      - "--env"
      - "SECRET_KEY=${_SECRET_KEY}"
      - "--env"
      - "GOOGLE_RECAPTCHA_SECRET_KEY=${_GOOGLE_RECAPTCHA_SECRET_KEY}"
      - "--network=cloudbuild"
      - "-v"
      - "/cloudsql:/cloudsql"
      - "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"
      - "python"
      - "manage.py"
      - "migrate"
    id: migrate
    waitFor:
      - setup_db
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"]
    id: push_image
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "${_ENV_NAME}"
      - "--image"
      - "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "SECRET_KEY=${_SECRET_KEY},GOOGLE_RECAPTCHA_SECRET_KEY=${_GOOGLE_RECAPTCHA_SECRET_KEY},DB_HOST=${_DB_HOST},DB_NAME=${_DB_NAME},DB_USER=${_DB_USER},DB_PASSWORD=${_DB_PASSWORD},DEBUG=${_DEBUG},GS_BUCKET_NAME=${_GS_BUCKET_NAME}"
    id: deploy
images:
  - "gcr.io/$PROJECT_ID/${_ENV_NAME}:latest"